### ISSUE TITLE
Something wrong when I tried to extract features 

### ISSUE THREAD

**Issue by AjianIronSide** [RicherMans/Datadriven-GPVAD#3]
Hi,

Something wrong when I tried to extract features with "python extract_feature.py wavs.txt -o hdf5/balanced.h5"

Traceback (most recent call last):
  File "extract_feature.py", line 86, in <module>
    DF[ARGS.col].unique(),
  File "/data/anaconda3/envs/gpvad/lib/python3.6/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/data/anaconda3/envs/gpvad/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'filename'

Is the pandas version wrong or something else?
Plz help. Thx

**Comment by RicherMans** [comment]
Whoops, seems to be a minor error.
Just assure your waves.txt has as it's first line `filename`

**Comment by AjianIronSide** [comment]
You are right. Thanks!
